### ISSUE TITLE
todo example crashes when opening localhost:3000 in browser

### ISSUE THREAD

**Issue by arekkas** [Originate/exosphere-sdk#149]
```
$ ~/.npm-packages/bin/exo run
Exosphere SDK 0.8.1

Running Todo application 0.0.1

   exocom  online at port 8000
     todo  Exosphere Node.js service runner 0.15.0
     todo  Running todo 0.0.1
     todo  /Users/aeneas/workspaces/go/src/github.com/ory-am/editor-platform/editor-platform/todo-app/todo/src/server.js
     todo  MongoDB 'exosphere-todo-service-dev' connected
     todo  Ctrl-C to stop
     todo  online at port 8002
   exorun  'todo' is running using exorelay port 8002
      web  ExoRelay online at port 8003
      web  HTML server online at port 3000
      web  all systems go
   exorun  'web' is running using exorelay port 8003
   exorun  all services online
   exocom  received routing setup
   exocom  [ todo.create ]  -->  todo (localhost:8002)
   exocom  [ todo.create_many ]  -->  todo (localhost:8002)
   exocom  [ todo.delete ]  -->  todo (localhost:8002)
   exocom  [ todo.list ]  -->  todo (localhost:8002)
   exocom  [ todo.read ]  -->  todo (localhost:8002)
   exocom  [ todo.update ]  -->  todo (localhost:8002)
   exocom  [ todo.created ]  -->  web (localhost:8003)
   exocom  [ todo.listing ]  -->  web (localhost:8003)
   exorun  application ready
events.js:160
      throw er; // Unhandled 'error' event
      ^

SyntaxError: Unexpected token e in JSON at position 0
    at Object.parse (native)
    at ZMQListener.onSocketReceive (/Users/aeneas/.npm-packages/lib/node_modules/exosphere-sdk/node_modules/exocom-dev/dist/listener-subsystem/zmq-listener.js:45:43)
    at .<anonymous> (/Users/aeneas/.npm-packages/lib/node_modules/exosphere-sdk/node_modules/exocom-dev/dist/listener-subsystem/zmq-listener.js:87:50)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at Socket._flushRead (/Users/aeneas/.npm-packages/lib/node_modules/exosphere-sdk/node_modules/zmq/lib/index.js:636:10)
    at Socket._flushReads (/Users/aeneas/.npm-packages/lib/node_modules/exosphere-sdk/node_modules/zmq/lib/index.js:676:23)
    at _zmq.onReadReady (/Users/aeneas/.npm-packages/lib/node_modules/exosphere-sdk/node_modules/zmq/lib/index.js:297:10)
```

**Comment by kevgo** [comment]
This is fixed now
