### ISSUE TITLE
don't panic if no receivers for a message are registered

### ISSUE THREAD

**Issue by arekkas** [Originate/exosphere-sdk#151]
currently, exosphere terminates if a message has no receivers, instead it should show a warning/error

```

   exocom     {}
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: No receivers for message 'pong' registered
    at ClientRegistry.subscribersTo (/Users/aeneas/.npm-packages/lib/node_modules/exosphere-sdk/node_modules/exocom-dev/dist/client-registry/client-registry.js:46:13)
    at ExoCom.sendMessage (/Users/aeneas/.npm-packages/lib/node_modules/exosphere-sdk/node_modules/exocom-dev/dist/exocom.js:54:39)

```

**Comment by arekkas** [comment]
oh and it looks like the services aren't terminated, because if I want to restart my app with `exo run` i get:

```
   exocom  online at port 8000
        a  Exosphere Node.js service runner 0.15.1
        a  Running a 0.0.1
        b  Exosphere Node.js service runner 0.15.1
        b  Running b 0.0.1
        a  /Users/aeneas/workspaces/go/src/github.com/ory-am/editor-platform/editor-platform/footest/foobar/a/src/server.js
        a  Address already in use
        b  /Users/aeneas/workspaces/go/src/github.com/ory-am/editor-platform/editor-platform/footest/foobar/b/src/server.js
        b  Address already in use
        c  Address already in use
        c  port 8004 for ExoRelay is already in use
        a  port 8002 for ExoRelay is already in use
        b  port 8003 for ExoRelay is already in use

```

**Comment by trushton** [comment]
The issue of services not being terminated correctly has been resolved with the move to Docker.

**Comment by kevgo** [comment]
Thanks @arekkas. We really have to get a new release out, there are tons of improvements: websockets, docker, AWS deployments.
